version: '3.8'

services:
  ott-client:
    build: ./ott-client
    ports:
      - "3000:80"
    depends_on:
      - node-server

  watchparty-client:
    build: ./watchparty-client
    ports:
      - "4000:80"
    depends_on:
      - node-server

  node-server:
    build: ./gemini-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  python-script:
    build: ./recommendation-model
    volumes:
      - ./recommendation-model:/app
    environment:
      - PYTHONUNBUFFERED=1
